sudo: required
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install libglade2-dev ghc-7.10.2 cabal-install-1.22
  - export PATH=/opt/ghc/7.10.2/bin:/opt/cabal/1.22/bin:$PATH
install:
  - travis_retry cabal update
  - cabal install alex happy
  - cabal install gtk2hs-buildtools
script:
  - cabal install
