language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install -qq libglade2-dev alex happy
install:
  - travis_retry cabal update
  - cabal install gtk2hs-buildtools
script:
  - cabal install
