language: haskell
ghc: 7.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install -qq libglade2-dev
install:
  - travis_retry cabal update
  - cabal install alex happy
  - cabal install gtk2hs-buildtools
script:
  - cabal install
